### ISSUE TITLE
Lack of License Information

### ISSUE THREAD

**Issue by pennro-se** [lospec/lospec-discord-bot#4]
A License should be chosen and added to the root of the repository in a file named `LICENSE`.

**Comment by PixelDud** [comment]
May I recommend the [MIT license](https://mit-license.org/).

**Comment by ghost** [comment]
May I recommend the [GPLv2 license](https://choosealicense.com/licenses/gpl-2.0/).

**Comment by PixelDud** [comment]
> May I recommend the [GPLv2 license](https://choosealicense.com/licenses/gpl-2.0/).

After reading over the conditions of the GPLv2 license I would say that would be of better use than the MIT license.

**Comment by ghost** [comment]
I think it would be easier to find a fitting license if we focused on what the people "can" do with the program and the source. And then add restrictions of top of that.
